service: earea-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-central-1:249409715289:table/sensors-alerts

functions:
  processSound:
    handler: handlers/processSound.handler
    events:
      - httpApi:
          path: /process/sound
          method: post

  saveAlert:
    handler: handlers/saveAlert.handler

  executeAlert:
    handler: handlers/executeAlert.handler
    events:
      - httpApi:
          path: /executeAlert
          method: post

  getLastNotifications:
    handler: handlers/getNotifications.handler
    events:
      - httpApi:
          path: /getNotifications
          method: get

  getIsNotificationsEnabled:
    handler: handlers/getIsNotificationsEnabled.handler
    events:
      - httpApi:
          path: /NotificationStatus
          method: get

  getSensorsList:
    handler: handlers/getSensorsList.handler
    events:
      - httpApi:
          path: /getSensors
          method: get
resources:
  Resources:
    serviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sensors-alerts
        AttributeDefinitions:
          - AttributeName: sensor-name
            AttributeType: S
          - AttributeName: alert-date
            AttributeType: S
        KeySchema:
          - AttributeName: sensor-name
            KeyType: HASH
          - AttributeName: alert-date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST