service: earea-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  processSound:
    handler: handlers/processSound.handler
    events:
      - httpApi:
          path: /process/sound
          method: get

  saveAlert:
    handler: handlers/saveAlert.handler

  executeAlert:
    handler: handlers/executeAlert.handler
    events:
      - httpApi:
          path: /executeAlert
          method: post

  getLastNotifications:
    handler: handlers/getNotifications.handler
    events:
      - httpApi:
          path: /getNotifications
          method: get

  getIsNotificationsEnabled:
    handler: handlers/getIsNotificationsEnabled.handler
    events:
      - httpApi:
          path: /NotificationStatus
          method: get

  getSensorsList:
    handler: handlers/getSensorsList.handler
    events:
      - httpApi:
          path: /getSensors
          method: get