service: earea-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:eu-central-1:249409715289:table/*

functions:
  processSound:
    handler: handlers/processSound.handler
    events:
      - httpApi:
          path: /process/sound
          method: post

  saveAlert:
    handler: handlers/saveAlert.handler

  executeAlert:
    handler: handlers/executeAlert.handler
    events:
      - httpApi:
          path: /executeAlert
          method: post

  getLastNotifications:
    handler: handlers/getNotifications.handler
    events:
      - httpApi:
          path: /getNotifications
          method: get

  getSettings:
    handler: handlers/getSettings.handler
    events:
      - httpApi:
          path: /getSettings
          method: get

  setSettings:
    handler: handlers/setSettings.handler
    events:
      - httpApi:
          path: /setSettings
          method: post

  getSensorsList:
    handler: handlers/getSensorsList.handler
    events:
      - httpApi:
          path: /getSensors
          method: get
resources:
  Resources:
    serviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: alertsDB
        AttributeDefinitions:
          - AttributeName: timeStamp
            AttributeType: S
          - AttributeName: sensorName
            AttributeType: S
        KeySchema:
          - AttributeName: timeStamp
            KeyType: HASH
          - AttributeName: sensorName
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    SoundData:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: soundData
          AttributeDefinitions:
            - AttributeName: values
              AttributeType: S
          KeySchema:
            - AttributeName: values
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST
    SettingsData:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: settingsDB
        AttributeDefinitions:
          - AttributeName: fieldName
            AttributeType: S
        KeySchema:
          - AttributeName: fieldName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST