service: earea-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  hello:
    handler: handlers/hello.handler
    events:
      - httpApi:
          path: /
          method: get
