export const strings = {
  TAB_HOME_SCREEN_LABEL: 'Home',
  TAB_SETTINGS_SCREEN_LABEL: 'Settings',
  TAB_DEMO_LABEL: 'Demo',
  HOME_SCREEN_TITLE: 'Earea',
  HOME_SCREEN_NOTIFICATIONS_TITLE: 'Last notifications',
  HOME_SCREEN_SENSORS_TITLE: 'Sensors',
  SETTINGS_SCREEN_TITLE: 'Settings',
  SETTINGS_SCREEN_NOTIFICATIONS_TITLE: 'Notifications',
  SETTINGS_SCREEN_SENSORS_TITLE: 'Sensors',
  DEMO_SCREEN_TEXT: 'Demo Screen',
};
